backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "settings"
    label: "Site Settings"
    files: 
      - label: "Site Settings"
        name: "settings"        
        extension: "json"
        file: "content/settings.json"        
        fields: 
          - {label: "Site Title", name: "site_title", widget: "string"}
          - {label: "Site Icon", name: "site_icon", widget: "image"}
          - label: "NavBar"
            name: "navbar"
            widget: "object"
            fields: 
              - {label: "Wallet Link", name: "navbar_wallet_link", widget: "string"}
              - {label: "Wallet Text", name: "navbar_wallet_text", widget: "string"}
              - {label: "Logo", name: "navbar_logo", widget: "image"}
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields: 
              - {label: "Hero Title", name: "hero_title", widget: "string"}
              - {label: "Hero Description", name: "hero_description", widget: "string"}
          - label: "Main Section (Featured Product - NFT)"
            name: "main"
            widget: "object"
            fields: 
              - {label: "Featured Product (ID)", name: "main_featured_product", widget: "string"}
              - {label: "Placeholder Image", name: "main_placeholder_image", widget: "image"}
              - {label: "Placeholder SaleType", name: "main_placeholder_saletype", widget: "string"}
              - {label: "Placeholder Status", name: "main_placeholder_status", widget: "string"}
              - {label: "Placeholder Title", name: "main_placeholder_title", widget: "string"}
              - {label: "Placeholder Price", name: "main_placeholder_price", widget: "number"}

          - label: "About Drop Section"
            name: "about"
            widget: "object"
            fields: 
              - {label: "About Title", name: "about_title", widget: "string"}
              - {label: "About Description", name: "about_description", widget: "string"}
          - label: "Gallery Drop Section"
            name: "gallery"
            widget: "list"
            fields:
              - {label: "Image", name: "gallery_image", widget: "image" }
          - label: "Contact section"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Twitter Link", name: "contact_twitter", widget: "string", required: false }
              - {label: "Instagram Link", name: "contact_instagram", widget: "string", required: false }
              - {label: "Discord Link", name: "contact_discord", widget: "string", required: false }
              - {label: "Tiktok Link", name: "contact_tiktok", widget: "string", required: false }
              - {label: "Telegram Link", name: "contact_telegram", widget: "string", required: false }
              - {label: "Reddit Link", name: "contact_reddit", widget: "string", required: false }



      

