backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "settings"
    label: "Site Settings"
    files: 
      - label: "Site Settings"
        name: "settings"        
        extension: "json"
        file: "content/settings.json"        
        fields: 
          - {label: "Site Title", name: "site_title", widget: "string"}
          - {label: "Site Icon", name: "site_icon", widget: "image"}
          - {label: "Appearance", name: "appearance", widget: "select", options: ["dark", "light"]}
          - {label: "Primary Color", name: "primary_color", widget: "string", hint: "list colors, css or hex color"}
          - {label: "Secondary Color", name: "secondary_color", widget: "select", options: ["white", "black"], default: "white" ,  hint: "list colors, css or hex color"}
          - label: "Local Fonts"
            name: "local_fonts"
            widget: "object"
            fields: 
              - {label: "Headline", name: "local_headline", widget: "select", options: ["Interstate","NeueMachina","Matter SQ","Pangram Sans","Eiko","Acherus"], required: false }
              - {label: "Body", name: "local_body", widget: "select", options: ["Interstate","NeueMachina","Matter SQ","Pangram Sans","Eiko","Acherus"], required: false }
          - label: "External Fonts"
            name: "external_fonts"
            widget: "object"
            fields: 
              - label: "Headline"
                name: "external_headline"
                widget: "object"
                fields:
                  - {label: "URL", name: "url_headline", widget: "string", required: false}
                  - {label: "Font family", name: "fontFamily_headline", widget: "string", required: false}
              - label: "Body"
                name: "external_body"
                widget: "object"
                fields:
                  - {label: "URL", name: "url_body", widget: "string", required: false}
                  - {label: "Font family", name: "fontFamily_body", widget: "string", required: false}
          - {label: "Button Shape", name: "button_shape", widget: "select", options: ["none","smooth","full"]}
          - label: "NavBar"
            name: "navbar"
            widget: "object"
            fields: 
              - {label: "Wallet Link", name: "navbar_wallet_link", widget: "string"}
              - {label: "Wallet Text", name: "navbar_wallet_text", widget: "string"}
              - {label: "Logo", name: "navbar_logo", widget: "image"}
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields: 
              - {label: "Hero Title", name: "hero_title", widget: "string"}
              - {label: "Hero Description", name: "hero_description", widget: "string"}
          - label: "Main Section (Featured Product)"
            name: "main"
            widget: "object"
            fields: 
              - {label: "Featured Product (ID)", name: "main_featured_product", widget: "string"}
          - label: "About Drop Section"
            name: "about"
            widget: "object"
            fields: 
              - {label: "About Title", name: "about_title", widget: "string"}
              - {label: "About Description", name: "about_description", widget: "string"}
          - label: "Gallery Drop Section"
            name: "gallery"
            widget: "list"
            fields:
              - {label: "Image", name: "gallery_image", widget: "image" }
          - label: "Contact section"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Twitter Link", name: "contact_twitter", widget: "string", required: false }
              - {label: "Instagram Link", name: "contact_instagram", widget: "string", required: false }
              - {label: "Discord Link", name: "contact_discord", widget: "string", required: false }
              - {label: "Tiktok Link", name: "contact_tiktok", widget: "string", required: false }
              - {label: "Telegram Link", name: "contact_telegram", widget: "string", required: false }
              - {label: "Reddit Link", name: "contact_reddit", widget: "string", required: false }



      

